; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = ESP32-S3
;default_envs = ESP32-S3-MINI

[env:ESP32-S3-MINI]
    platform = espressif32
    framework = arduino
    monitor_speed = 115200

;https://esp32async.github.io/ESPAsyncWebServer/configuration/
    build_flags =
        -DBOARD_HAS_PSRAM
        -D ARDUINO_USB_CDC_ON_BOOT=1
        -D LED_PIN=21
        -DESP32_S3_MINI
        -D CONFIG_ASYNC_TCP_MAX_ACK_TIME=5000
        -D CONFIG_ASYNC_TCP_PRIORITY=10
        -D CONFIG_ASYNC_TCP_QUEUE_SIZE=64
        -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
        -D CONFIG_ASYNC_TCP_STACK_SIZE=4096
    lib_deps =
        fastled/FastLED @ ^3.6.0
        esp32async/ESPAsyncWebServer@^3.10.3

    board = esp32-s3-devkitc-1
    board_build.partitions=default.csv
    board_build.arduino.memory_type = qio_qspi
    board_build.flash_mode = qio
    board_build.psram_type = qio
    board_upload.flash_size = 4MB
    board_upload.maximum_size = 4194304

[env:ESP32-S3]
    platform = espressif32
    framework = arduino
    monitor_speed = 115200

    build_flags =
        -DUSE_BLE
        -DUSE_ROTARY
        -DBOARD_HAS_PSRAM
        -D ARDUINO_USB_CDC_ON_BOOT=1
        -D LED_PIN=48
        -DESP32_S3

    lib_deps =
        fastled/FastLED @ ^3.6.0
        esp32async/ESPAsyncWebServer@^3.10.3
        lennarthennigs/ESP Rotary@^2.1.1

    board = esp32-s3-devkitc-1
